// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvsLMldMQUc-h_K6ICNJuH85b6-Ofhg_4',
    appId: '1:221759892375:web:46f70c2290b3e1926b32d2',
    messagingSenderId: '221759892375',
    projectId: 'todoapp-84fd8',
    authDomain: 'todoapp-84fd8.firebaseapp.com',
    storageBucket: 'todoapp-84fd8.firebasestorage.app',
    measurementId: 'G-EZP0K41X5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVOrRfWMW48I4OcKUPJCAQkGHj0Q9oW0c',
    appId: '1:221759892375:android:8daff2a003b2f8e56b32d2',
    messagingSenderId: '221759892375',
    projectId: 'todoapp-84fd8',
    storageBucket: 'todoapp-84fd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcouUuBfgx0KZBXEqRXnvtTTLwmwV2r0Q',
    appId: '1:221759892375:ios:bcdeadc0255a5fc16b32d2',
    messagingSenderId: '221759892375',
    projectId: 'todoapp-84fd8',
    storageBucket: 'todoapp-84fd8.firebasestorage.app',
    iosBundleId: 'com.example.flutterBasics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcouUuBfgx0KZBXEqRXnvtTTLwmwV2r0Q',
    appId: '1:221759892375:ios:bcdeadc0255a5fc16b32d2',
    messagingSenderId: '221759892375',
    projectId: 'todoapp-84fd8',
    storageBucket: 'todoapp-84fd8.firebasestorage.app',
    iosBundleId: 'com.example.flutterBasics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvsLMldMQUc-h_K6ICNJuH85b6-Ofhg_4',
    appId: '1:221759892375:web:0cdf07174bcd3d406b32d2',
    messagingSenderId: '221759892375',
    projectId: 'todoapp-84fd8',
    authDomain: 'todoapp-84fd8.firebaseapp.com',
    storageBucket: 'todoapp-84fd8.firebasestorage.app',
    measurementId: 'G-9JP35VF5C1',
  );
}
